
var _ = require('underscore');

var moves =
[
   {
      "stop" : "1050",
      "start" : "850",
      "stamLoss" : "0.01",
      "power" : "10",
      "duration" : "1050",
      "name" : "Acid",
      "type" : "Poison",
      "energy" : "10",
      "fx" : "acid_fast",
      "trainerMin" : "1",
      "ID" : "225",
      "accuracy" : "1",
      "animation" : "4",
      "trainerMax" : "100"
   },
   {
      "stop" : "500",
      "stamLoss" : "0.01",
      "start" : "300",
      "power" : "6",
      "duration" : "500",
      "type" : "Dark",
      "energy" : "7",
      "trainerMin" : "1",
      "fx" : "bite_fast",
      "accuracy" : "1",
      "ID" : "202",
      "name" : "Bite",
      "animation" : "4",
      "trainerMax" : "100"
   },
   {
      "energy" : "25",
      "type" : "Water",
      "trainerMin" : "1",
      "fx" : "bubble_fast",
      "accuracy" : "1",
      "ID" : "237",
      "name" : "Bubble",
      "trainerMax" : "100",
      "animation" : "4",
      "stop" : "2300",
      "stamLoss" : "0.01",
      "start" : "2100",
      "power" : "25",
      "duration" : "2300"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "name" : "Bug Bite",
      "fx" : "bug_bite_fast",
      "trainerMin" : "1",
      "ID" : "201",
      "accuracy" : "1",
      "energy" : "7",
      "type" : "Bug",
      "power" : "5",
      "duration" : "450",
      "start" : "250",
      "stop" : "450",
      "stamLoss" : "0.01"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "type" : "Steel",
      "energy" : "10",
      "fx" : "bullet_punch_fast",
      "trainerMin" : "1",
      "ID" : "229",
      "accuracy" : "1",
      "name" : "Bullet Punch",
      "power" : "10",
      "duration" : "1200",
      "stamLoss" : "0.01",
      "stop" : "1200",
      "start" : "1000"
   },
   {
      "fx" : "confusion_fast",
      "accuracy" : "1",
      "trainerMin" : "1",
      "ID" : "235",
      "energy" : "14",
      "type" : "Psychic",
      "name" : "Confusion",
      "animation" : "4",
      "trainerMax" : "100",
      "stamLoss" : "0.01",
      "stop" : "1510",
      "start" : "1310",
      "power" : "15",
      "duration" : "1510"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "name" : "Cut",
      "type" : "Normal",
      "energy" : "10",
      "trainerMin" : "1",
      "fx" : "cut_fast",
      "accuracy" : "1",
      "ID" : "223",
      "duration" : "1130",
      "power" : "12",
      "start" : "930",
      "stop" : "1130",
      "stamLoss" : "0.01"
   },
   {
      "stop" : "500",
      "stamLoss" : "0.01",
      "start" : "300",
      "duration" : "500",
      "power" : "6",
      "name" : "Dragon Breath",
      "type" : "Dragon",
      "energy" : "7",
      "fx" : "dragon_breath_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "204",
      "animation" : "4",
      "trainerMax" : "100"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Ember",
      "type" : "Fire",
      "energy" : "10",
      "trainerMin" : "1",
      "fx" : "ember_fast",
      "accuracy" : "1",
      "ID" : "209",
      "power" : "10",
      "duration" : "1050",
      "stop" : "1050",
      "stamLoss" : "0.01",
      "start" : "850"
   },
   {
      "type" : "Dark",
      "energy" : "10",
      "trainerMin" : "1",
      "fx" : "feint_attack_fast",
      "ID" : "238",
      "accuracy" : "1",
      "name" : "Feint Attack",
      "animation" : "4",
      "trainerMax" : "100",
      "stop" : "1040",
      "start" : "840",
      "stamLoss" : "0.01",
      "duration" : "1040",
      "power" : "12"
   },
   {
      "duration" : "840",
      "power" : "10",
      "start" : "640",
      "stop" : "840",
      "stamLoss" : "0.01",
      "trainerMax" : "100",
      "animation" : "4",
      "type" : "Fire",
      "energy" : "8",
      "fx" : "fire_fang_fast",
      "trainerMin" : "1",
      "ID" : "240",
      "accuracy" : "1",
      "name" : "Fire Fang"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Frost Breath",
      "energy" : "7",
      "type" : "Ice",
      "ID" : "218",
      "fx" : "frost_breath_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "duration" : "810",
      "power" : "9",
      "stop" : "810",
      "stamLoss" : "0.01",
      "start" : "610"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Fury Cutter",
      "energy" : "6",
      "type" : "Bug",
      "fx" : "fury_cutter_fast",
      "trainerMin" : "1",
      "ID" : "200",
      "accuracy" : "1",
      "duration" : "400",
      "power" : "3",
      "start" : "200",
      "stop" : "400",
      "stamLoss" : "0.01"
   },
   {
      "trainerMin" : "1",
      "fx" : "ice_shard_fast",
      "ID" : "217",
      "accuracy" : "1",
      "type" : "Ice",
      "energy" : "12",
      "name" : "Ice Shard",
      "trainerMax" : "100",
      "animation" : "4",
      "stamLoss" : "0.01",
      "stop" : "1400",
      "start" : "1200",
      "power" : "15",
      "duration" : "1400"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Karate Chop",
      "fx" : "karate_chop_fast",
      "trainerMin" : "1",
      "ID" : "208",
      "accuracy" : "1",
      "energy" : "8",
      "type" : "Fighting",
      "power" : "6",
      "duration" : "800",
      "stamLoss" : "0.01",
      "stop" : "800",
      "start" : "600"
   },
   {
      "start" : "300",
      "stop" : "500",
      "stamLoss" : "0.01",
      "power" : "5",
      "duration" : "500",
      "name" : "Lick",
      "type" : "Ghost",
      "energy" : "6",
      "fx" : "lick_fast",
      "trainerMin" : "1",
      "ID" : "212",
      "accuracy" : "1",
      "trainerMax" : "100",
      "animation" : "4"
   },
   {
      "stamLoss" : "0.01",
      "stop" : "600",
      "start" : "400",
      "duration" : "600",
      "power" : "5",
      "name" : "Low Kick",
      "type" : "Fighting",
      "energy" : "7",
      "fx" : "low_kick_fast",
      "trainerMin" : "1",
      "ID" : "207",
      "accuracy" : "1",
      "trainerMax" : "100",
      "animation" : "4"
   },
   {
      "stamLoss" : "0.01",
      "stop" : "630",
      "start" : "430",
      "duration" : "630",
      "power" : "8",
      "name" : "Metal Claw",
      "fx" : "metal_claw_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "228",
      "type" : "Steel",
      "energy" : "7",
      "animation" : "4",
      "trainerMax" : "100"
   },
   {
      "duration" : "550",
      "power" : "6",
      "stamLoss" : "0.01",
      "stop" : "550",
      "start" : "350",
      "animation" : "4",
      "trainerMax" : "100",
      "energy" : "7",
      "type" : "Ground",
      "fx" : "mud_shot_fast",
      "trainerMin" : "1",
      "ID" : "216",
      "accuracy" : "1",
      "name" : "Mud Shot"
   },
   {
      "name" : "Mud Slap",
      "type" : "Ground",
      "energy" : "12",
      "fx" : "mud_slap_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "233",
      "trainerMax" : "100",
      "animation" : "4",
      "stop" : "1350",
      "stamLoss" : "0.01",
      "start" : "1150",
      "duration" : "1350",
      "power" : "15"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "trainerMin" : "1",
      "fx" : "peck_fast",
      "ID" : "211",
      "accuracy" : "1",
      "energy" : "10",
      "type" : "Flying",
      "name" : "Peck",
      "power" : "10",
      "duration" : "1150",
      "stop" : "1150",
      "stamLoss" : "0.01",
      "start" : "950"
   },
   {
      "stop" : "1050",
      "stamLoss" : "0.01",
      "start" : "850",
      "duration" : "1050",
      "power" : "12",
      "name" : "Poison Jab",
      "trainerMin" : "1",
      "fx" : "poison_jab_fast",
      "accuracy" : "1",
      "ID" : "224",
      "energy" : "10",
      "type" : "Poison",
      "trainerMax" : "100",
      "animation" : "4"
   },
   {
      "fx" : "poison_sting_fast",
      "trainerMin" : "1",
      "ID" : "236",
      "accuracy" : "1",
      "energy" : "8",
      "type" : "Poison",
      "name" : "Poison Sting",
      "trainerMax" : "100",
      "animation" : "4",
      "stop" : "575",
      "start" : "375",
      "stamLoss" : "0.01",
      "power" : "6",
      "duration" : "575"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "fx" : "pound_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "222",
      "type" : "Normal",
      "energy" : "7",
      "name" : "Pound",
      "power" : "7",
      "duration" : "540",
      "start" : "340",
      "stop" : "540",
      "stamLoss" : "0.01"
   },
   {
      "duration" : "570",
      "power" : "7",
      "start" : "370",
      "stop" : "570",
      "stamLoss" : "0.01",
      "animation" : "4",
      "trainerMax" : "100",
      "fx" : "psycho_cut_fast",
      "trainerMin" : "1",
      "ID" : "226",
      "accuracy" : "1",
      "type" : "Psychic",
      "energy" : "7",
      "name" : "Psycho Cut"
   },
   {
      "name" : "Quick Attack",
      "fx" : "quick_attack_fast",
      "trainerMin" : "1",
      "ID" : "219",
      "accuracy" : "1",
      "energy" : "12",
      "type" : "Normal",
      "animation" : "4",
      "trainerMax" : "100",
      "stamLoss" : "0.01",
      "stop" : "1330",
      "start" : "1130",
      "duration" : "1330",
      "power" : "10"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Razor Leaf",
      "energy" : "12",
      "type" : "Grass",
      "trainerMin" : "1",
      "fx" : "razor_leaf_fast",
      "ID" : "215",
      "accuracy" : "1",
      "power" : "15",
      "duration" : "1450",
      "start" : "1250",
      "stop" : "1450",
      "stamLoss" : "0.01"
   },
   {
      "duration" : "1410",
      "power" : "15",
      "stamLoss" : "0.01",
      "stop" : "1410",
      "start" : "1210",
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Rock Smash",
      "ID" : "241",
      "fx" : "rock_smash_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "type" : "Fighting",
      "energy" : "12"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "name" : "Rock Throw",
      "energy" : "15",
      "type" : "Rock",
      "fx" : "rock_throw_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "227",
      "duration" : "1360",
      "power" : "12",
      "stop" : "1360",
      "start" : "1160",
      "stamLoss" : "0.01"
   },
   {
      "stop" : "500",
      "stamLoss" : "0.01",
      "start" : "300",
      "power" : "6",
      "duration" : "500",
      "type" : "Normal",
      "energy" : "7",
      "trainerMin" : "1",
      "fx" : "scratch_fast",
      "accuracy" : "1",
      "ID" : "220",
      "name" : "Scratch",
      "animation" : "4",
      "trainerMax" : "100"
   },
   {
      "energy" : "8",
      "type" : "Ghost",
      "fx" : "shadow_claw_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "213",
      "name" : "Shadow Claw",
      "animation" : "4",
      "trainerMax" : "100",
      "stop" : "950",
      "stamLoss" : "0.01",
      "start" : "750",
      "power" : "11",
      "duration" : "950"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "trainerMin" : "1",
      "fx" : "spark_fast",
      "accuracy" : "1",
      "ID" : "206",
      "type" : "Electric",
      "energy" : "8",
      "name" : "Spark",
      "duration" : "700",
      "power" : "7",
      "stamLoss" : "0.01",
      "stop" : "700",
      "start" : "500"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "name" : "Splash",
      "energy" : "10",
      "type" : "Water",
      "ID" : "231",
      "fx" : "splash_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "duration" : "1230",
      "power" : "0",
      "stop" : "1230",
      "stamLoss" : "0.01",
      "start" : "1030"
   },
   {
      "trainerMin" : "1",
      "fx" : "steel_wing_fast",
      "ID" : "239",
      "accuracy" : "1",
      "type" : "Steel",
      "energy" : "12",
      "name" : "Steel Wing",
      "animation" : "4",
      "trainerMax" : "100",
      "stop" : "1330",
      "stamLoss" : "0.01",
      "start" : "1130",
      "duration" : "1330",
      "power" : "15"
   },
   {
      "animation" : "4",
      "trainerMax" : "100",
      "fx" : "sucker_punch_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "203",
      "energy" : "9",
      "type" : "Dark",
      "name" : "Sucker Punch",
      "power" : "7",
      "duration" : "700",
      "stamLoss" : "0.01",
      "stop" : "700",
      "start" : "500"
   },
   {
      "name" : "Tackle",
      "accuracy" : "1",
      "fx" : "tackle_fast",
      "trainerMin" : "1",
      "ID" : "221",
      "type" : "Normal",
      "energy" : "10",
      "animation" : "4",
      "trainerMax" : "100",
      "stop" : "1100",
      "start" : "900",
      "stamLoss" : "0.01",
      "power" : "12",
      "duration" : "1100"
   },
   {
      "name" : "Thunder Shock",
      "fx" : "thunder_shock_fast",
      "ID" : "205",
      "trainerMin" : "1",
      "accuracy" : "1",
      "energy" : "8",
      "type" : "Electric",
      "animation" : "4",
      "trainerMax" : "100",
      "stamLoss" : "0.01",
      "stop" : "600",
      "start" : "400",
      "duration" : "600",
      "power" : "5"
   },
   {
      "stop" : "650",
      "stamLoss" : "0.01",
      "start" : "450",
      "duration" : "650",
      "power" : "7",
      "type" : "Grass",
      "energy" : "7",
      "accuracy" : "1",
      "fx" : "vine_whip_fast",
      "trainerMin" : "1",
      "ID" : "214",
      "name" : "Vine Whip",
      "trainerMax" : "100",
      "animation" : "4"
   },
   {
      "type" : "Water",
      "energy" : "7",
      "fx" : "water_gun_fast",
      "trainerMin" : "1",
      "accuracy" : "1",
      "ID" : "230",
      "name" : "Water Gun",
      "trainerMax" : "100",
      "animation" : "4",
      "start" : "300",
      "stop" : "500",
      "stamLoss" : "0.01",
      "duration" : "500",
      "power" : "6"
   },
   {
      "name" : "Wing Attack",
      "trainerMin" : "1",
      "fx" : "wing_attack_fast",
      "ID" : "210",
      "accuracy" : "1",
      "energy" : "7",
      "type" : "Flying",
      "trainerMax" : "100",
      "animation" : "4",
      "stamLoss" : "0.01",
      "stop" : "750",
      "start" : "550",
      "duration" : "750",
      "power" : "9"
   },
   {
      "trainerMax" : "100",
      "animation" : "4",
      "fx" : "zen_headbutt_fast",
      "accuracy" : "1",
      "trainerMin" : "1",
      "ID" : "234",
      "type" : "Psychic",
      "energy" : "9",
      "name" : "Zen Headbutt",
      "power" : "12",
      "duration" : "1050",
      "stop" : "1050",
      "stamLoss" : "0.01",
      "start" : "850"
   }
];

var lookup = {
  byId : {},
  byName : {},
};

_.each(moves, function (data) {
  lookup.byId[data.ID] = data;
  lookup.byName[data.name.toLowerCase()] = data;
});


module.exports = {
	allMoves : function () {
		return moves.slice();
	},
  moveByName : function (name) {
    return lookup.byName[(name + '').toLowerCase()];
  },
  moveById : function (id) {
    var moveId = parseInt(id, 10);
    return lookup.byId[moveId];
  }
};
