
var _ = require('underscore');

var moves =

[
   {
      "end" : "3400",
      "pwr" : "25",
      "durMS" : "4000",
      "name" : "Wrap",
      "stamLoss" : "0.06",
      "type" : "Normal",
      "start" : "2800",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-20",
      "heal" : "0"
   },
   {
      "acc" : "1",
      "energyDelta" : "-100",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "4800",
      "durMS" : "5000",
      "pwr" : "120",
      "start" : "4000",
      "type" : "Normal",
      "stamLoss" : "0.15",
      "name" : "Hyper Beam"
   },
   {
      "heal" : "0",
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "type" : "Dark",
      "start" : "2300",
      "stamLoss" : "0.08",
      "name" : "Dark Pulse",
      "durMS" : "3500",
      "pwr" : "45",
      "end" : "3400"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1",
      "stamLoss" : "0.065",
      "name" : "Sludge",
      "type" : "Poison",
      "start" : "1850",
      "pwr" : "30",
      "durMS" : "2600",
      "end" : "2350"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "start" : "1850",
      "type" : "Normal",
      "stamLoss" : "0.055",
      "name" : "Vice Grip",
      "durMS" : "2100",
      "pwr" : "25",
      "end" : "2100"
   },
   {
      "stamLoss" : "0.06",
      "name" : "Flame Wheel",
      "start" : "2700",
      "type" : "Fire",
      "pwr" : "40",
      "durMS" : "4600",
      "end" : "3200",
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1"
   },
   {
      "heal" : "0",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05",
      "start" : "2400",
      "type" : "Bug",
      "name" : "Megahorn",
      "stamLoss" : "0.12",
      "end" : "2700",
      "durMS" : "3200",
      "pwr" : "80"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-50",
      "heal" : "0",
      "end" : "2600",
      "pwr" : "55",
      "durMS" : "2900",
      "stamLoss" : "0.09",
      "name" : "Flamethrower",
      "type" : "Fire",
      "start" : "1700"
   },
   {
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05",
      "heal" : "0",
      "durMS" : "5800",
      "pwr" : "70",
      "end" : "5000",
      "type" : "Ground",
      "start" : "4600",
      "name" : "Dig",
      "stamLoss" : "0.08"
   },
   {
      "durMS" : "2000",
      "pwr" : "60",
      "end" : "1800",
      "type" : "Fighting",
      "start" : "1500",
      "name" : "Cross Chop",
      "stamLoss" : "0.1",
      "acc" : "1",
      "energyDelta" : "-100",
      "crit" : "0.25",
      "heal" : "0"
   },
   {
      "end" : "3600",
      "pwr" : "40",
      "durMS" : "3800",
      "name" : "Psybeam",
      "stamLoss" : "0.065",
      "start" : "2300",
      "type" : "Psychic",
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "start" : "2000",
      "type" : "Ground",
      "stamLoss" : "0.1",
      "name" : "Earthquake",
      "durMS" : "4200",
      "pwr" : "100",
      "end" : "3950",
      "heal" : "0",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "crit" : "0.5",
      "energyDelta" : "-100",
      "acc" : "1",
      "heal" : "0",
      "pwr" : "80",
      "durMS" : "3100",
      "end" : "1800",
      "stamLoss" : "0.1",
      "name" : "Stone Edge",
      "start" : "1400",
      "type" : "Rock"
   },
   {
      "durMS" : "3500",
      "pwr" : "45",
      "end" : "3200",
      "start" : "2100",
      "type" : "Ice",
      "stamLoss" : "0.075",
      "name" : "Ice Punch",
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "durMS" : "2550",
      "pwr" : "20",
      "end" : "2250",
      "start" : "1950",
      "type" : "Psychic",
      "name" : "Heart Stamp",
      "stamLoss" : "0.06",
      "acc" : "1",
      "energyDelta" : "-25",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "heal" : "0",
      "end" : "2300",
      "pwr" : "35",
      "durMS" : "2500",
      "name" : "Discharge",
      "stamLoss" : "0.08",
      "type" : "Electric",
      "start" : "1600"
   },
   {
      "pwr" : "60",
      "durMS" : "3900",
      "end" : "3500",
      "name" : "Flash Cannon",
      "stamLoss" : "0.08",
      "type" : "Steel",
      "start" : "2400",
      "crit" : "0.05",
      "energyDelta" : "-33",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "pwr" : "40",
      "durMS" : "2700",
      "end" : "2500",
      "stamLoss" : "0.08",
      "name" : "Drill Peck",
      "start" : "1600",
      "type" : "Flying",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "heal" : "0"
   },
   {
      "acc" : "1",
      "energyDelta" : "-50",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "3500",
      "durMS" : "3650",
      "pwr" : "65",
      "type" : "Ice",
      "start" : "2150",
      "stamLoss" : "0.09",
      "name" : "Ice Beam"
   },
   {
      "end" : "3600",
      "pwr" : "100",
      "durMS" : "3900",
      "name" : "Blizzard",
      "stamLoss" : "0.11",
      "start" : "3600",
      "type" : "Ice",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-100",
      "heal" : "0"
   },
   {
      "type" : "Fire",
      "start" : "3000",
      "stamLoss" : "0.095",
      "name" : "Heat Wave",
      "end" : "3400",
      "durMS" : "3800",
      "pwr" : "80",
      "heal" : "0",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "acc" : "1",
      "energyDelta" : "-25",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "2600",
      "durMS" : "2900",
      "pwr" : "30",
      "start" : "2000",
      "type" : "Flying",
      "name" : "Aerial Ace",
      "stamLoss" : "0.06"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.25",
      "start" : "2100",
      "type" : "Ground",
      "name" : "Drill Run",
      "stamLoss" : "0.08",
      "end" : "2800",
      "durMS" : "3400",
      "pwr" : "50"
   },
   {
      "crit" : "0.05",
      "energyDelta" : "-50",
      "acc" : "1",
      "heal" : "0",
      "pwr" : "65",
      "durMS" : "3200",
      "end" : "3100",
      "name" : "Petal Blizzard",
      "stamLoss" : "0.09",
      "type" : "Grass",
      "start" : "2100"
   },
   {
      "start" : "1400",
      "type" : "Grass",
      "name" : "Mega Drain",
      "stamLoss" : "0.04",
      "durMS" : "3200",
      "pwr" : "15",
      "end" : "2600",
      "heal" : "0.5",
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05"
   },
   {
      "heal" : "0",
      "energyDelta" : "-50",
      "acc" : "1",
      "crit" : "0.05",
      "start" : "2600",
      "type" : "Bug",
      "name" : "Bug Buzz",
      "stamLoss" : "0.09",
      "durMS" : "4250",
      "pwr" : "75",
      "end" : "4100"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "start" : "1650",
      "type" : "Poison",
      "stamLoss" : "0.05",
      "name" : "Poison Fang",
      "end" : "1850",
      "durMS" : "2400",
      "pwr" : "25"
   },
   {
      "name" : "Night Slash",
      "stamLoss" : "0.07",
      "type" : "Dark",
      "start" : "2400",
      "pwr" : "30",
      "durMS" : "2700",
      "end" : "2600",
      "heal" : "0",
      "crit" : "0.25",
      "acc" : "1",
      "energyDelta" : "-25"
   },
   {
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1",
      "heal" : "0",
      "end" : "2800",
      "pwr" : "30",
      "durMS" : "2900",
      "stamLoss" : "0.065",
      "name" : "Bubble Beam",
      "type" : "Water",
      "start" : "2600"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "stamLoss" : "0.08",
      "name" : "Submission",
      "type" : "Fighting",
      "start" : "1850",
      "end" : "2000",
      "pwr" : "30",
      "durMS" : "2100"
   },
   {
      "name" : "Low Sweep",
      "stamLoss" : "0.065",
      "start" : "2000",
      "type" : "Fighting",
      "end" : "2150",
      "pwr" : "30",
      "durMS" : "2250",
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-25"
   },
   {
      "durMS" : "2350",
      "pwr" : "25",
      "end" : "2100",
      "type" : "Water",
      "start" : "1700",
      "name" : "Aqua Jet",
      "stamLoss" : "0.04",
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "type" : "Water",
      "start" : "2050",
      "stamLoss" : "0.09",
      "name" : "Aqua Tail",
      "durMS" : "2350",
      "pwr" : "45",
      "end" : "2250",
      "heal" : "0",
      "energyDelta" : "-50",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "type" : "Grass",
      "start" : "1300",
      "stamLoss" : "0.08",
      "name" : "Seed Bomb",
      "durMS" : "2400",
      "pwr" : "40",
      "end" : "1800",
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "name" : "Psyshock",
      "stamLoss" : "0.08",
      "start" : "2200",
      "type" : "Psychic",
      "pwr" : "40",
      "durMS" : "2700",
      "end" : "2700"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-25",
      "crit" : "0.05",
      "type" : "Rock",
      "start" : "2900",
      "stamLoss" : "0.06",
      "name" : "Ancient Power",
      "durMS" : "3600",
      "pwr" : "35",
      "end" : "3250"
   },
   {
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.25",
      "heal" : "0",
      "end" : "3200",
      "durMS" : "3400",
      "pwr" : "30",
      "start" : "2300",
      "type" : "Rock",
      "stamLoss" : "0.06",
      "name" : "Rock Tomb"
   },
   {
      "end" : "2900",
      "pwr" : "50",
      "durMS" : "3200",
      "name" : "Rock Slide",
      "stamLoss" : "0.075",
      "start" : "1500",
      "type" : "Rock",
      "crit" : "0.05",
      "energyDelta" : "-33",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0",
      "durMS" : "2900",
      "pwr" : "40",
      "end" : "2800",
      "start" : "2000",
      "type" : "Rock",
      "name" : "Power Gem",
      "stamLoss" : "0.08"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-20",
      "name" : "Shadow Sneak",
      "stamLoss" : "0.04",
      "start" : "2300",
      "type" : "Ghost",
      "pwr" : "15",
      "durMS" : "3100",
      "end" : "2900"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-25",
      "heal" : "0",
      "pwr" : "20",
      "durMS" : "2100",
      "end" : "1700",
      "name" : "Shadow Punch",
      "stamLoss" : "0.06",
      "type" : "Ghost",
      "start" : "1400"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-25",
      "crit" : "0.05",
      "start" : "1850",
      "type" : "Ghost",
      "stamLoss" : "0.06",
      "name" : "Ominous Wind",
      "durMS" : "3100",
      "pwr" : "30",
      "end" : "2100"
   },
   {
      "end" : "2600",
      "durMS" : "3080",
      "pwr" : "45",
      "type" : "Ghost",
      "start" : "2300",
      "name" : "Shadow Ball",
      "stamLoss" : "0.08",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "heal" : "0",
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.05",
      "type" : "Steel",
      "start" : "1750",
      "name" : "Magnet Bomb",
      "stamLoss" : "0.06",
      "durMS" : "2800",
      "pwr" : "30",
      "end" : "2300"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05",
      "type" : "Steel",
      "start" : "1550",
      "name" : "Iron Head",
      "stamLoss" : "0.08",
      "durMS" : "2000",
      "pwr" : "30",
      "end" : "1800"
   },
   {
      "end" : "1700",
      "durMS" : "2100",
      "pwr" : "15",
      "start" : "1300",
      "type" : "Electric",
      "stamLoss" : "0.05",
      "name" : "Parabolic Charge",
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "heal" : "0.5"
   },
   {
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "2200",
      "durMS" : "2400",
      "pwr" : "40",
      "type" : "Electric",
      "start" : "1950",
      "stamLoss" : "0.075",
      "name" : "Thunder Punch"
   },
   {
      "pwr" : "100",
      "durMS" : "4300",
      "end" : "4100",
      "name" : "Thunder",
      "stamLoss" : "0.11",
      "start" : "2550",
      "type" : "Electric",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-100",
      "heal" : "0"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-50",
      "acc" : "1",
      "stamLoss" : "0.09",
      "name" : "Thunderbolt",
      "type" : "Electric",
      "start" : "1900",
      "pwr" : "55",
      "durMS" : "2700",
      "end" : "2700"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-20",
      "name" : "Twister",
      "stamLoss" : "0.04",
      "start" : "850",
      "type" : "Dragon",
      "pwr" : "25",
      "durMS" : "2700",
      "end" : "2600"
   },
   {
      "crit" : "0.05",
      "energyDelta" : "-50",
      "acc" : "1",
      "heal" : "0",
      "pwr" : "65",
      "durMS" : "3600",
      "end" : "3300",
      "stamLoss" : "0.085",
      "name" : "Dragon Pulse",
      "type" : "Dragon",
      "start" : "2100"
   },
   {
      "acc" : "1",
      "energyDelta" : "-50",
      "crit" : "0.25",
      "heal" : "0",
      "durMS" : "1500",
      "pwr" : "35",
      "end" : "1400",
      "type" : "Dragon",
      "start" : "1200",
      "name" : "Dragon Claw",
      "stamLoss" : "0.08"
   },
   {
      "type" : "Fairy",
      "start" : "1800",
      "name" : "Disarming Voice",
      "stamLoss" : "0.04",
      "durMS" : "3900",
      "pwr" : "25",
      "end" : "3600",
      "heal" : "0",
      "energyDelta" : "-20",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "name" : "Draining Kiss",
      "stamLoss" : "0.05",
      "start" : "1000",
      "type" : "Fairy",
      "pwr" : "25",
      "durMS" : "2800",
      "end" : "1100",
      "heal" : "1",
      "crit" : "0.05",
      "energyDelta" : "-20",
      "acc" : "1"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "heal" : "0",
      "end" : "4100",
      "pwr" : "55",
      "durMS" : "4200",
      "name" : "Dazzling Gleam",
      "stamLoss" : "0.08",
      "type" : "Fairy",
      "start" : "3300"
   },
   {
      "heal" : "0",
      "acc" : "1",
      "energyDelta" : "-100",
      "crit" : "0.05",
      "type" : "Fairy",
      "start" : "3500",
      "name" : "Moonblast",
      "stamLoss" : "0.095",
      "end" : "4100",
      "durMS" : "4100",
      "pwr" : "85"
   },
   {
      "end" : "2700",
      "durMS" : "2900",
      "pwr" : "55",
      "type" : "Fairy",
      "start" : "1400",
      "name" : "Play Rough",
      "stamLoss" : "0.1",
      "acc" : "1",
      "energyDelta" : "-50",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "pwr" : "25",
      "durMS" : "1500",
      "end" : "1500",
      "name" : "Cross Poison",
      "stamLoss" : "0.07",
      "start" : "1200",
      "type" : "Poison",
      "crit" : "0.25",
      "energyDelta" : "-25",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "pwr" : "55",
      "durMS" : "2600",
      "end" : "2450",
      "stamLoss" : "0.09",
      "name" : "Sludge Bomb",
      "type" : "Poison",
      "start" : "1950",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-50",
      "heal" : "0"
   },
   {
      "durMS" : "3400",
      "pwr" : "70",
      "end" : "3300",
      "type" : "Poison",
      "start" : "2400",
      "name" : "Sludge Wave",
      "stamLoss" : "0.095",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "end" : "2400",
      "pwr" : "65",
      "durMS" : "3000",
      "name" : "Gunk Shot",
      "stamLoss" : "0.12",
      "type" : "Poison",
      "start" : "2000",
      "crit" : "0.05",
      "energyDelta" : "-100",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "heal" : "0",
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.05",
      "type" : "Ground",
      "start" : "1250",
      "stamLoss" : "0.065",
      "name" : "Bone Club",
      "end" : "1500",
      "durMS" : "1600",
      "pwr" : "25"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-25",
      "heal" : "0",
      "pwr" : "35",
      "durMS" : "3400",
      "end" : "3000",
      "name" : "Bulldoze",
      "stamLoss" : "0.06",
      "start" : "1900",
      "type" : "Ground"
   },
   {
      "name" : "Mud Bomb",
      "stamLoss" : "0.065",
      "type" : "Ground",
      "start" : "2050",
      "end" : "2500",
      "pwr" : "30",
      "durMS" : "2600",
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1"
   },
   {
      "heal" : "0",
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "start" : "2000",
      "type" : "Bug",
      "stamLoss" : "0.075",
      "name" : "Signal Beam",
      "end" : "3000",
      "durMS" : "3100",
      "pwr" : "45"
   },
   {
      "stamLoss" : "0.08",
      "name" : "X Scissor",
      "start" : "1350",
      "type" : "Bug",
      "pwr" : "35",
      "durMS" : "2100",
      "end" : "1600",
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33"
   },
   {
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "heal" : "0",
      "durMS" : "3100",
      "pwr" : "25",
      "end" : "2900",
      "start" : "2700",
      "type" : "Fire",
      "name" : "Flame Charge",
      "stamLoss" : "0.05"
   },
   {
      "type" : "Fire",
      "start" : "1200",
      "name" : "Flame Burst",
      "stamLoss" : "0.07",
      "end" : "1600",
      "durMS" : "2100",
      "pwr" : "30",
      "heal" : "0",
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "4000",
      "durMS" : "4100",
      "pwr" : "100",
      "type" : "Fire",
      "start" : "3600",
      "name" : "Fire Blast",
      "stamLoss" : "0.11"
   },
   {
      "stamLoss" : "0.065",
      "name" : "Brine",
      "type" : "Water",
      "start" : "1650",
      "end" : "2000",
      "pwr" : "25",
      "durMS" : "2400",
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-25"
   },
   {
      "acc" : "1",
      "energyDelta" : "-25",
      "crit" : "0.05",
      "heal" : "0",
      "end" : "2900",
      "durMS" : "3300",
      "pwr" : "35",
      "type" : "Water",
      "start" : "1900",
      "name" : "Water Pulse",
      "stamLoss" : "0.06"
   },
   {
      "durMS" : "4000",
      "pwr" : "55",
      "end" : "3900",
      "type" : "Water",
      "start" : "1800",
      "stamLoss" : "0.08",
      "name" : "Scald",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "durMS" : "3800",
      "pwr" : "90",
      "end" : "3600",
      "start" : "1500",
      "type" : "Water",
      "name" : "Hydro Pump",
      "stamLoss" : "0.11",
      "acc" : "1",
      "energyDelta" : "-100",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "end" : "2800",
      "pwr" : "55",
      "durMS" : "2800",
      "name" : "Psychic",
      "stamLoss" : "0.09",
      "start" : "1600",
      "type" : "Psychic",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-50",
      "heal" : "0"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-100",
      "acc" : "1",
      "name" : "Psystrike",
      "stamLoss" : "0.1",
      "start" : "4400",
      "type" : "Psychic",
      "end" : "5300",
      "pwr" : "70",
      "durMS" : "5100"
   },
   {
      "end" : "2700",
      "pwr" : "25",
      "durMS" : "3800",
      "stamLoss" : "0.055",
      "name" : "Icy Wind",
      "type" : "Ice",
      "start" : "2000",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-20",
      "heal" : "0"
   },
   {
      "end" : "1500",
      "durMS" : "3600",
      "pwr" : "35",
      "start" : "350",
      "type" : "Grass",
      "name" : "Giga Drain",
      "stamLoss" : "0.075",
      "acc" : "1",
      "energyDelta" : "-33",
      "crit" : "0.05",
      "heal" : "0.5"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33",
      "heal" : "0",
      "end" : "2200",
      "pwr" : "40",
      "durMS" : "2800",
      "stamLoss" : "0.075",
      "name" : "Fire Punch",
      "type" : "Fire",
      "start" : "1690"
   },
   {
      "durMS" : "4900",
      "pwr" : "120",
      "end" : "4800",
      "start" : "3100",
      "type" : "Grass",
      "name" : "Solar Beam",
      "stamLoss" : "0.12",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "heal" : "0",
      "crit" : "0.25",
      "acc" : "1",
      "energyDelta" : "-50",
      "stamLoss" : "0.09",
      "name" : "Leaf Blade",
      "start" : "1200",
      "type" : "Grass",
      "pwr" : "55",
      "durMS" : "2800",
      "end" : "2200"
   },
   {
      "name" : "Power Whip",
      "stamLoss" : "0.12",
      "start" : "1500",
      "type" : "Grass",
      "end" : "2800",
      "pwr" : "70",
      "durMS" : "2800",
      "heal" : "0",
      "crit" : "0",
      "energyDelta" : "-100",
      "acc" : "1"
   },
   {
      "type" : "Flying",
      "start" : "2200",
      "name" : "Air Cutter",
      "stamLoss" : "0.06",
      "end" : "3100",
      "durMS" : "3300",
      "pwr" : "30",
      "heal" : "0",
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.25"
   },
   {
      "durMS" : "3200",
      "pwr" : "80",
      "end" : "2800",
      "type" : "Flying",
      "start" : "1030",
      "stamLoss" : "0.11",
      "name" : "Hurricane",
      "acc" : "1",
      "energyDelta" : "-100",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "pwr" : "30",
      "durMS" : "1600",
      "end" : "1500",
      "name" : "Brick Break",
      "stamLoss" : "0.075",
      "start" : "1100",
      "type" : "Fighting",
      "crit" : "0.25",
      "acc" : "1",
      "energyDelta" : "-33",
      "heal" : "0"
   },
   {
      "durMS" : "3000",
      "pwr" : "30",
      "end" : "2800",
      "start" : "2300",
      "type" : "Normal",
      "stamLoss" : "0.06",
      "name" : "Swift",
      "energyDelta" : "-25",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-25",
      "heal" : "0",
      "pwr" : "25",
      "durMS" : "2200",
      "end" : "1900",
      "name" : "Horn Attack",
      "stamLoss" : "0.065",
      "start" : "1600",
      "type" : "Normal"
   },
   {
      "end" : "1900",
      "pwr" : "30",
      "durMS" : "2100",
      "name" : "Stomp",
      "stamLoss" : "0.065",
      "start" : "1200",
      "type" : "Normal",
      "crit" : "0.05",
      "energyDelta" : "-25",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "end" : "2000",
      "durMS" : "2100",
      "pwr" : "35",
      "type" : "Normal",
      "start" : "1700",
      "stamLoss" : "0.08",
      "name" : "Hyper Fang",
      "energyDelta" : "-33",
      "acc" : "1",
      "crit" : "0.05",
      "heal" : "0"
   },
   {
      "end" : "1300",
      "pwr" : "40",
      "durMS" : "1560",
      "stamLoss" : "0.085",
      "name" : "Body Slam",
      "start" : "1100",
      "type" : "Normal",
      "crit" : "0.05",
      "energyDelta" : "-50",
      "acc" : "1",
      "heal" : "0"
   },
   {
      "name" : "Rest",
      "stamLoss" : "0",
      "type" : "Normal",
      "start" : "1395",
      "end" : "2691",
      "pwr" : "35",
      "durMS" : "3100",
      "heal" : "1",
      "crit" : "0",
      "energyDelta" : "-33",
      "acc" : "1"
   },
   {
      "crit" : "0",
      "energyDelta" : "-20",
      "acc" : "1",
      "heal" : "0",
      "pwr" : "15",
      "durMS" : "1695",
      "end" : "1500",
      "stamLoss" : "0.1",
      "name" : "Struggle",
      "start" : "800",
      "type" : "Normal"
   },
   {
      "name" : "SCALD BLASTOISE",
      "stamLoss" : "0.08",
      "start" : "1800",
      "type" : "Water",
      "end" : "3900",
      "pwr" : "55",
      "durMS" : "4000",
      "heal" : "0",
      "crit" : "0.05",
      "acc" : "1",
      "energyDelta" : "-33"
   },
   {
      "start" : "1500",
      "type" : "Water",
      "name" : "HYDRO PUMP BLASTOISE",
      "stamLoss" : "0.11",
      "end" : "3600",
      "durMS" : "3800",
      "pwr" : "90",
      "heal" : "0",
      "energyDelta" : "-100",
      "acc" : "1",
      "crit" : "0.05"
   },
   {
      "acc" : "1",
      "energyDelta" : "-20",
      "crit" : "0.05",
      "heal" : "0",
      "durMS" : "3700",
      "pwr" : "25",
      "end" : "3200",
      "start" : "2200",
      "type" : "Normal",
      "name" : "WRAP GREEN",
      "stamLoss" : "0.06"
   },
   {
      "heal" : "0",
      "crit" : "0.05",
      "energyDelta" : "-20",
      "acc" : "1",
      "stamLoss" : "0.06",
      "name" : "WRAP PINK",
      "start" : "2200",
      "type" : "Normal",
      "end" : "3200",
      "pwr" : "25",
      "durMS" : "3700"
   }
];

var lookup = {
  byName : {},
};

_.each(moves, function (data) {
  lookup.byName[data.name.toLowerCase()] = data;
});


module.exports = {
   allMoves : function () {
      return moves.slice();
   },
  moveByName : function (name) {
    return lookup.byName[(name + '').toLowerCase()];
  }
};


